using BookWarehouse.Domain.Entities;
using BookWarehouse.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;

namespace BookWarehouse.Infrastructure.Persistence.Seeders
{
    public class ProductSeeder(ApplicationDbContext dbContext) : IProductSeeder
    {
        private readonly ApplicationDbContext _dbContext = dbContext;

        public async Task SeedAsync()
        {
            if (await _dbContext.Database.CanConnectAsync())
            {
                if (!_dbContext.Products.Any())
                {
                    var categories = await _dbContext.Categories.ToDictionaryAsync(c => c.Name, c => c.Id);
                    var products = new List<Product>();

                    int GetCatId(string name) => categories.TryGetValue(name, out int id) ? id : categories.Values.FirstOrDefault();

                    // Novels
                    int novelsId = GetCatId("Novels");
                    products.Add(new Product { Title = "The Great Gatsby", Author = "F. Scott Fitzgerald", ISBN = "978-0743273565", Description = "A story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan.", ListPrice = 15.99m, Price = 14.99m, Price50 = 13.99m, Price100 = 12.99m, ImageUrl = "", CategoryId = novelsId });
                    products.Add(new Product { Title = "To Kill a Mockingbird", Author = "Harper Lee", ISBN = "978-0060935467", Description = "Compassionate, dramatic, and deeply moving, taking readers to the roots of human behavior.", ListPrice = 18.99m, Price = 17.50m, Price50 = 16.50m, Price100 = 15.00m, ImageUrl = "", CategoryId = novelsId });
                    products.Add(new Product { Title = "1984", Author = "George Orwell", ISBN = "978-0451524935", Description = "Among the seminal texts of the 20th century, 1984 is a rare work that grows more haunting as its futuristic purgatory becomes more real.", ListPrice = 19.99m, Price = 18.99m, Price50 = 17.99m, Price100 = 16.50m, ImageUrl = "", CategoryId = novelsId });
                    products.Add(new Product { Title = "Pride and Prejudice", Author = "Jane Austen", ISBN = "978-1503290563", Description = "A romantic novel of manners written by Jane Austen in 1813.", ListPrice = 14.99m, Price = 13.50m, Price50 = 12.00m, Price100 = 11.00m, ImageUrl = "", CategoryId = novelsId });
                    products.Add(new Product { Title = "The Catcher in the Rye", Author = "J.D. Salinger", ISBN = "978-0316769174", Description = "A novel by J. D. Salinger, partially published in serial form in 1945–1946 and as a novel in 1951.", ListPrice = 16.99m, Price = 15.99m, Price50 = 14.50m, Price100 = 13.00m, ImageUrl = "", CategoryId = novelsId });
                    products.Add(new Product { Title = "The Lord of the Rings", Author = "J.R.R. Tolkien", ISBN = "978-0544003415", Description = "An epic high fantasy novel written by English author and scholar J. R. R. Tolkien.", ListPrice = 35.00m, Price = 32.00m, Price50 = 30.00m, Price100 = 28.00m, ImageUrl = "", CategoryId = novelsId });
                    products.Add(new Product { Title = "Jane Eyre", Author = "Charlotte Brontë", ISBN = "978-0141441146", Description = "A novel by English writer Charlotte Brontë, published under the pen name Currer Bell.", ListPrice = 12.99m, Price = 11.99m, Price50 = 10.99m, Price100 = 9.99m, ImageUrl = "", CategoryId = novelsId });
                    products.Add(new Product { Title = "Animal Farm", Author = "George Orwell", ISBN = "978-0451526342", Description = "A satirical allegorical novella by George Orwell, first published in England on 17 August 1945.", ListPrice = 14.99m, Price = 13.99m, Price50 = 12.50m, Price100 = 11.50m, ImageUrl = "", CategoryId = novelsId });

                    // Children's Books
                    int childrensId = GetCatId("Children's Books");
                    products.Add(new Product { Title = "Harry Potter and the Sorcerer's Stone", Author = "J.K. Rowling", ISBN = "978-0590353427", Description = "Harry Potter has never played a sport while flying on a broomstick.", ListPrice = 24.99m, Price = 22.99m, Price50 = 20.99m, Price100 = 18.99m, ImageUrl = "", CategoryId = childrensId });
                    products.Add(new Product { Title = "Where the Wild Things Are", Author = "Maurice Sendak", ISBN = "978-0060254926", Description = "The story of Max, who wears a wolf suit and makes mischief of one kind and another.", ListPrice = 19.95m, Price = 18.50m, Price50 = 17.00m, Price100 = 15.50m, ImageUrl = "", CategoryId = childrensId });
                    products.Add(new Product { Title = "Charlotte's Web", Author = "E.B. White", ISBN = "978-0061124952", Description = "The tale of how a little girl named Fern, with the help of a friendly spider, saved her pig Wilbur.", ListPrice = 12.99m, Price = 11.50m, Price50 = 10.50m, Price100 = 9.00m, ImageUrl = "", CategoryId = childrensId });
                    products.Add(new Product { Title = "The Very Hungry Caterpillar", Author = "Eric Carle", ISBN = "978-0399226908", Description = "A picture book with die-cut pages, featuring a caterpillar that eats its way through a variety of foods.", ListPrice = 10.99m, Price = 9.99m, Price50 = 8.50m, Price100 = 7.50m, ImageUrl = "", CategoryId = childrensId });
                    products.Add(new Product { Title = "Green Eggs and Ham", Author = "Dr. Seuss", ISBN = "978-0394800165", Description = "Sam-I-am tries to convince his friend to eat green eggs and ham.", ListPrice = 11.99m, Price = 10.99m, Price50 = 9.50m, Price100 = 8.50m, ImageUrl = "", CategoryId = childrensId });
                    products.Add(new Product { Title = "Winnie-the-Pooh", Author = "A.A. Milne", ISBN = "978-0140361216", Description = "The classic stories about a bear of very little brain and his friends.", ListPrice = 14.99m, Price = 13.99m, Price50 = 12.00m, Price100 = 11.00m, ImageUrl = "", CategoryId = childrensId });
                    products.Add(new Product { Title = "The Tale of Peter Rabbit", Author = "Beatrix Potter", ISBN = "978-0723247708", Description = "The classic tale of a mischievous rabbit in Mr. McGregor's garden.", ListPrice = 9.99m, Price = 8.99m, Price50 = 7.99m, Price100 = 6.99m, ImageUrl = "", CategoryId = childrensId });
                    products.Add(new Product { Title = "Matilda", Author = "Roald Dahl", ISBN = "978-0142410370", Description = "The story of a very smart girl with terrible parents and magical powers.", ListPrice = 13.99m, Price = 12.50m, Price50 = 11.00m, Price100 = 10.00m, ImageUrl = "", CategoryId = childrensId });

                    // Science
                    int scienceId = GetCatId("Science");
                    products.Add(new Product { Title = "A Brief History of Time", Author = "Stephen Hawking", ISBN = "978-0553380163", Description = "A landmark volume in science writing by one of the great minds of our time.", ListPrice = 18.00m, Price = 16.50m, Price50 = 15.00m, Price100 = 13.50m, ImageUrl = "", CategoryId = scienceId });
                    products.Add(new Product { Title = "The Selfish Gene", Author = "Richard Dawkins", ISBN = "978-0192860927", Description = "A book on evolution by Richard Dawkins, published in 1976.", ListPrice = 19.95m, Price = 18.00m, Price50 = 16.50m, Price100 = 15.00m, ImageUrl = "", CategoryId = scienceId });
                    products.Add(new Product { Title = "Cosmos", Author = "Carl Sagan", ISBN = "978-0345331359", Description = "The story of fifteen billion years of cosmic evolution transforming matter and life into consciousness.", ListPrice = 22.00m, Price = 20.00m, Price50 = 18.50m, Price100 = 17.00m, ImageUrl = "", CategoryId = scienceId });
                    products.Add(new Product { Title = "The Origin of Species", Author = "Charles Darwin", ISBN = "978-0451529060", Description = "The foundational text of the biological sciences, detailing the theory of evolution by natural selection.", ListPrice = 15.00m, Price = 13.50m, Price50 = 12.00m, Price100 = 10.50m, ImageUrl = "", CategoryId = scienceId });
                    products.Add(new Product { Title = "The Double Helix", Author = "James D. Watson", ISBN = "978-0743216302", Description = "A personal account of the discovery of the structure of DNA.", ListPrice = 17.99m, Price = 16.00m, Price50 = 14.50m, Price100 = 13.00m, ImageUrl = "", CategoryId = scienceId });
                    products.Add(new Product { Title = "Silent Spring", Author = "Rachel Carson", ISBN = "978-0618249060", Description = "An environmental science book documenting the adverse environmental effects caused by pesticides.", ListPrice = 16.99m, Price = 15.50m, Price50 = 14.00m, Price100 = 12.50m, ImageUrl = "", CategoryId = scienceId });
                    products.Add(new Product { Title = "Thinking, Fast and Slow", Author = "Daniel Kahneman", ISBN = "978-0374533557", Description = "A major book about cognitive biases, intuition, and decision making.", ListPrice = 20.00m, Price = 18.50m, Price50 = 17.00m, Price100 = 15.50m, ImageUrl = "", CategoryId = scienceId });
                    products.Add(new Product { Title = "Sapiens: A Brief History of Humankind", Author = "Yuval Noah Harari", ISBN = "978-0062316097", Description = "An exploration of how biology and history have defined us and enhanced our understanding of what it means to be human.", ListPrice = 24.99m, Price = 22.50m, Price50 = 20.00m, Price100 = 18.00m, ImageUrl = "", CategoryId = scienceId });

                    // History
                    int historyId = GetCatId("History");
                    products.Add(new Product { Title = "Guns, Germs, and Steel", Author = "Jared Diamond", ISBN = "978-0393317558", Description = "A short history of everybody for the last 13,000 years.", ListPrice = 21.00m, Price = 19.50m, Price50 = 18.00m, Price100 = 16.50m, ImageUrl = "", CategoryId = historyId });
                    products.Add(new Product { Title = "The Diary of a Young Girl", Author = "Anne Frank", ISBN = "978-0553296983", Description = "The writings from the Dutch-language diary kept by Anne Frank while she was in hiding.", ListPrice = 14.99m, Price = 13.50m, Price50 = 12.00m, Price100 = 10.50m, ImageUrl = "", CategoryId = historyId });
                    products.Add(new Product { Title = "A People's History of the United States", Author = "Howard Zinn", ISBN = "978-0060838652", Description = "A history of the United States from the point of view of the American people.", ListPrice = 22.99m, Price = 21.00m, Price50 = 19.50m, Price100 = 18.00m, ImageUrl = "", CategoryId = historyId });
                    products.Add(new Product { Title = "The Art of War", Author = "Sun Tzu", ISBN = "978-1590302255", Description = "An ancient Chinese military treatise dating from the Late Spring and Autumn Period.", ListPrice = 12.99m, Price = 11.50m, Price50 = 10.00m, Price100 = 8.50m, ImageUrl = "", CategoryId = historyId });
                    products.Add(new Product { Title = "The Rise and Fall of the Third Reich", Author = "William L. Shirer", ISBN = "978-1451651683", Description = "A history of Nazi Germany from 1933 to 1945.", ListPrice = 28.00m, Price = 26.00m, Price50 = 24.00m, Price100 = 22.00m, ImageUrl = "", CategoryId = historyId });
                    products.Add(new Product { Title = "Band of Brothers", Author = "Stephen E. Ambrose", ISBN = "978-0743224543", Description = "E Company, 506th Regiment, 101st Airborne from Normandy to Hitler's Eagle's Nest.", ListPrice = 19.99m, Price = 18.50m, Price50 = 17.00m, Price100 = 15.50m, ImageUrl = "", CategoryId = historyId });
                    products.Add(new Product { Title = "1776", Author = "David McCullough", ISBN = "978-0743226721", Description = "The story of those who marched with General George Washington in the year of the Declaration of Independence.", ListPrice = 20.00m, Price = 18.50m, Price50 = 17.00m, Price100 = 15.00m, ImageUrl = "", CategoryId = historyId });
                    products.Add(new Product { Title = "SPQR: A History of Ancient Rome", Author = "Mary Beard", ISBN = "978-1631492228", Description = "A sweeping, revisionist history of the Roman Empire.", ListPrice = 23.00m, Price = 21.00m, Price50 = 19.00m, Price100 = 17.00m, ImageUrl = "", CategoryId = historyId });

                    // Religion & Philosophy
                    int religionId = GetCatId("Religion & Philosophy");
                    products.Add(new Product { Title = "Meditations", Author = "Marcus Aurelius", ISBN = "978-0812968255", Description = "A series of personal writings by Marcus Aurelius, Roman Emperor from 161 to 180 AD.", ListPrice = 15.00m, Price = 13.50m, Price50 = 12.00m, Price100 = 10.50m, ImageUrl = "", CategoryId = religionId });
                    products.Add(new Product { Title = "The Republic", Author = "Plato", ISBN = "978-0140455113", Description = "A Socratic dialogue, written by Plato around 375 BC, concerning justice.", ListPrice = 14.99m, Price = 13.50m, Price50 = 12.00m, Price100 = 10.50m, ImageUrl = "", CategoryId = religionId });
                    products.Add(new Product { Title = "Beyond Good and Evil", Author = "Friedrich Nietzsche", ISBN = "978-0140449235", Description = "A comprehensive overview of Nietzsche's mature philosophy.", ListPrice = 16.99m, Price = 15.50m, Price50 = 14.00m, Price100 = 12.50m, ImageUrl = "", CategoryId = religionId });
                    products.Add(new Product { Title = "Tao Te Ching", Author = "Laozi", ISBN = "978-0060812454", Description = "A fundamental text for both philosophical and religious Taoism.", ListPrice = 12.99m, Price = 11.50m, Price50 = 10.00m, Price100 = 8.50m, ImageUrl = "", CategoryId = religionId });
                    products.Add(new Product { Title = "Mere Christianity", Author = "C.S. Lewis", ISBN = "978-0060652920", Description = "A theological book by C. S. Lewis, adapted from a series of BBC radio talks.", ListPrice = 17.99m, Price = 16.50m, Price50 = 15.00m, Price100 = 13.50m, ImageUrl = "", CategoryId = religionId });
                    products.Add(new Product { Title = "The Critique of Pure Reason", Author = "Immanuel Kant", ISBN = "978-0140447477", Description = "One of the most influential works in the history of philosophy.", ListPrice = 24.00m, Price = 22.00m, Price50 = 20.00m, Price100 = 18.00m, ImageUrl = "", CategoryId = religionId });
                    products.Add(new Product { Title = "The Screwtape Letters", Author = "C.S. Lewis", ISBN = "978-0060652937", Description = "A Christian apologetic novel by C. S. Lewis and dedicated to J. R. R. Tolkien.", ListPrice = 15.99m, Price = 14.50m, Price50 = 13.00m, Price100 = 11.50m, ImageUrl = "", CategoryId = religionId });
                    products.Add(new Product { Title = "Zen and the Art of Motorcycle Maintenance", Author = "Robert M. Pirsig", ISBN = "978-0060589462", Description = "An inquiry into values, exploring the Metaphysics of Quality.", ListPrice = 18.99m, Price = 17.50m, Price50 = 16.00m, Price100 = 14.50m, ImageUrl = "", CategoryId = religionId });

                    // Self-Help
                    int selfHelpId = GetCatId("Self-Help");
                    products.Add(new Product { Title = "Atomic Habits", Author = "James Clear", ISBN = "978-0735211292", Description = "An easy & proven way to build good habits & break bad ones.", ListPrice = 27.00m, Price = 24.50m, Price50 = 22.00m, Price100 = 19.50m, ImageUrl = "", CategoryId = selfHelpId });
                    products.Add(new Product { Title = "How to Win Friends and Influence People", Author = "Dale Carnegie", ISBN = "978-0671027032", Description = "The most famous confidence-boosting book ever published.", ListPrice = 18.99m, Price = 17.00m, Price50 = 15.50m, Price100 = 14.00m, ImageUrl = "", CategoryId = selfHelpId });
                    products.Add(new Product { Title = "The 7 Habits of Highly Effective People", Author = "Stephen R. Covey", ISBN = "978-1982137274", Description = "Powerful lessons in personal change.", ListPrice = 22.00m, Price = 20.00m, Price50 = 18.50m, Price100 = 17.00m, ImageUrl = "", CategoryId = selfHelpId });
                    products.Add(new Product { Title = "Man's Search for Meaning", Author = "Viktor E. Frankl", ISBN = "978-0807014295", Description = "Psychiatrist Viktor Frankl's memoir has riveted generations of readers with its descriptions of life in Nazi death camps.", ListPrice = 16.99m, Price = 15.50m, Price50 = 14.00m, Price100 = 12.50m, ImageUrl = "", CategoryId = selfHelpId });
                    products.Add(new Product { Title = "Think and Grow Rich", Author = "Napoleon Hill", ISBN = "978-1585424337", Description = "The landmark bestseller now revised and updated for the 21st century.", ListPrice = 14.99m, Price = 13.50m, Price50 = 12.00m, Price100 = 10.50m, ImageUrl = "", CategoryId = selfHelpId });
                    products.Add(new Product { Title = "The Power of Now", Author = "Eckhart Tolle", ISBN = "978-1577314806", Description = "A guide to spiritual enlightenment.", ListPrice = 19.95m, Price = 18.00m, Price50 = 16.50m, Price100 = 15.00m, ImageUrl = "", CategoryId = selfHelpId });
                    products.Add(new Product { Title = "Outliers: The Story of Success", Author = "Malcolm Gladwell", ISBN = "978-0316017930", Description = "An exploration of the world of \"outliers\"—the best and the brightest, the most famous and the most successful.", ListPrice = 21.99m, Price = 20.00m, Price50 = 18.50m, Price100 = 17.00m, ImageUrl = "", CategoryId = selfHelpId });
                    products.Add(new Product { Title = "Daring Greatly", Author = "Brené Brown", ISBN = "978-1592408412", Description = "How the courage to be vulnerable transforms the way we live, love, parent, and lead.", ListPrice = 20.00m, Price = 18.50m, Price50 = 17.00m, Price100 = 15.50m, ImageUrl = "", CategoryId = selfHelpId });

                    // Technology
                    int technologyId = GetCatId("Technology");
                    products.Add(new Product { Title = "The Innovators", Author = "Walter Isaacson", ISBN = "978-1476708706", Description = "How a group of hackers, geniuses, and geeks created the digital revolution.", ListPrice = 25.00m, Price = 22.50m, Price50 = 20.00m, Price100 = 18.00m, ImageUrl = "", CategoryId = technologyId });
                    products.Add(new Product { Title = "Clean Code", Author = "Robert C. Martin", ISBN = "978-0132350884", Description = "A Handbook of Agile Software Craftsmanship.", ListPrice = 45.00m, Price = 42.00m, Price50 = 39.00m, Price100 = 36.00m, ImageUrl = "", CategoryId = technologyId });
                    products.Add(new Product { Title = "The Pragmatic Programmer", Author = "Andrew Hunt", ISBN = "978-0135957059", Description = "Your journey to mastery in software development.", ListPrice = 49.99m, Price = 46.00m, Price50 = 43.00m, Price100 = 40.00m, ImageUrl = "", CategoryId = technologyId });
                    products.Add(new Product { Title = "Hackers: Heroes of the Computer Revolution", Author = "Steven Levy", ISBN = "978-1449388393", Description = "The definitive history of the early days of the computer revolution.", ListPrice = 24.99m, Price = 22.50m, Price50 = 20.00m, Price100 = 18.00m, ImageUrl = "", CategoryId = technologyId });
                    products.Add(new Product { Title = "Steve Jobs", Author = "Walter Isaacson", ISBN = "978-1451648539", Description = "The exclusive biography of Steve Jobs.", ListPrice = 30.00m, Price = 27.50m, Price50 = 25.00m, Price100 = 22.50m, ImageUrl = "", CategoryId = technologyId });
                    products.Add(new Product { Title = "Structure and Interpretation of Computer Programs", Author = "Harold Abelson", ISBN = "978-0262510875", Description = "A highly influential textbook in computer science.", ListPrice = 65.00m, Price = 60.00m, Price50 = 55.00m, Price100 = 50.00m, ImageUrl = "", CategoryId = technologyId });
                    products.Add(new Product { Title = "Design Patterns", Author = "Erich Gamma", ISBN = "978-0201633610", Description = "Elements of Reusable Object-Oriented Software.", ListPrice = 54.99m, Price = 50.00m, Price50 = 46.00m, Price100 = 42.00m, ImageUrl = "", CategoryId = technologyId });
                    products.Add(new Product { Title = "Code: The Hidden Language of Computer Hardware and Software", Author = "Charles Petzold", ISBN = "978-0735611313", Description = "A unique exploration into the workings of computers.", ListPrice = 29.99m, Price = 27.00m, Price50 = 24.50m, Price100 = 22.00m, ImageUrl = "", CategoryId = technologyId });

                    // Biographies
                    int biographiesId = GetCatId("Biographies");
                    products.Add(new Product { Title = "The Autobiography of Malcolm X", Author = "Malcolm X", ISBN = "978-0345350688", Description = "The result of a collaboration between Malcolm X and journalist Alex Haley.", ListPrice = 18.99m, Price = 17.00m, Price50 = 15.50m, Price100 = 14.00m, ImageUrl = "", CategoryId = biographiesId });
                    products.Add(new Product { Title = "Long Walk to Freedom", Author = "Nelson Mandela", ISBN = "978-0316548182", Description = "The autobiography of Nelson Mandela.", ListPrice = 22.00m, Price = 20.00m, Price50 = 18.50m, Price100 = 17.00m, ImageUrl = "", CategoryId = biographiesId });
                    products.Add(new Product { Title = "Becoming", Author = "Michelle Obama", ISBN = "978-1524763138", Description = "An intimate, powerful, and inspiring memoir by the former First Lady.", ListPrice = 32.50m, Price = 29.50m, Price50 = 27.00m, Price100 = 24.50m, ImageUrl = "", CategoryId = biographiesId });
                    products.Add(new Product { Title = "Alexander Hamilton", Author = "Ron Chernow", ISBN = "978-0143034759", Description = "A biography of American Statesman Alexander Hamilton.", ListPrice = 24.00m, Price = 22.00m, Price50 = 20.00m, Price100 = 18.00m, ImageUrl = "", CategoryId = biographiesId });
                    products.Add(new Product { Title = "Einstein: His Life and Universe", Author = "Walter Isaacson", ISBN = "978-0743264747", Description = "The definitive biography of Albert Einstein.", ListPrice = 23.00m, Price = 21.00m, Price50 = 19.00m, Price100 = 17.00m, ImageUrl = "", CategoryId = biographiesId });
                    products.Add(new Product { Title = "Leonardo da Vinci", Author = "Walter Isaacson", ISBN = "978-1501139154", Description = "A biography of the great Renaissance polymath.", ListPrice = 35.00m, Price = 32.00m, Price50 = 29.00m, Price100 = 26.00m, ImageUrl = "", CategoryId = biographiesId });
                    products.Add(new Product { Title = "Shoe Dog", Author = "Phil Knight", ISBN = "978-1501135927", Description = "A memoir by the creator of Nike.", ListPrice = 20.00m, Price = 18.50m, Price50 = 17.00m, Price100 = 15.50m, ImageUrl = "", CategoryId = biographiesId });
                    products.Add(new Product { Title = "The Wright Brothers", Author = "David McCullough", ISBN = "978-1476728759", Description = "The dramatic story-behind-the-story about the courageous brothers who taught the world how to fly.", ListPrice = 21.00m, Price = 19.50m, Price50 = 18.00m, Price100 = 16.50m, ImageUrl = "", CategoryId = biographiesId });

                    // Fantasy
                    int fantasyId = GetCatId("Fantasy");
                    products.Add(new Product { Title = "Harry Potter and the Chamber of Secrets", Author = "J.K. Rowling", ISBN = "978-0439064873", Description = "The Dursleys were so mean and hideous that summer that all Harry Potter wanted was to get back to the Hogwarts.", ListPrice = 24.99m, Price = 22.99m, Price50 = 20.99m, Price100 = 18.99m, ImageUrl = "", CategoryId = fantasyId });
                    products.Add(new Product { Title = "The Hobbit", Author = "J.R.R. Tolkien", ISBN = "978-0547928227", Description = "A great modern classic and the prelude to The Lord of the Rings.", ListPrice = 14.99m, Price = 13.50m, Price50 = 12.00m, Price100 = 10.50m, ImageUrl = "", CategoryId = fantasyId });
                    products.Add(new Product { Title = "A Game of Thrones", Author = "George R.R. Martin", ISBN = "978-0553593716", Description = "The first volume in A Song of Ice and Fire.", ListPrice = 18.99m, Price = 17.00m, Price50 = 15.50m, Price100 = 14.00m, ImageUrl = "", CategoryId = fantasyId });
                    products.Add(new Product { Title = "The Name of the Wind", Author = "Patrick Rothfuss", ISBN = "978-0756404741", Description = "The riveting first-person narrative of a young man who grows to be the most notorious magician his world has ever seen.", ListPrice = 19.99m, Price = 18.00m, Price50 = 16.50m, Price100 = 15.00m, ImageUrl = "", CategoryId = fantasyId });
                    products.Add(new Product { Title = "Mistborn: The Final Empire", Author = "Brandon Sanderson", ISBN = "978-0765350381", Description = "A heist story of political intrigue and magical, martial-arts action.", ListPrice = 17.99m, Price = 16.00m, Price50 = 14.50m, Price100 = 13.00m, ImageUrl = "", CategoryId = fantasyId });
                    products.Add(new Product { Title = "The Lies of Locke Lamora", Author = "Scott Lynch", ISBN = "978-0553588941", Description = "An orphan's life is harsh—and often short—in the mysterious island city of Camorr.", ListPrice = 16.99m, Price = 15.50m, Price50 = 14.00m, Price100 = 12.50m, ImageUrl = "", CategoryId = fantasyId });
                    products.Add(new Product { Title = "American Gods", Author = "Neil Gaiman", ISBN = "978-0062572233", Description = "A story of gods, old and new, and the battle for the soul of America.", ListPrice = 19.99m, Price = 18.00m, Price50 = 16.50m, Price100 = 15.00m, ImageUrl = "", CategoryId = fantasyId });
                    products.Add(new Product { Title = "The Color of Magic", Author = "Terry Pratchett", ISBN = "978-0062225672", Description = "The first book in the acclaimed Discworld series.", ListPrice = 15.99m, Price = 14.50m, Price50 = 13.00m, Price100 = 11.50m, ImageUrl = "", CategoryId = fantasyId });

                    // Mystery & Thriller
                    int mysteryId = GetCatId("Mystery & Thriller");
                    products.Add(new Product { Title = "Gone Girl", Author = "Gillian Flynn", ISBN = "978-0307588371", Description = "A toxic marriage and a thrilling psychological mystery.", ListPrice = 16.00m, Price = 14.50m, Price50 = 13.00m, Price100 = 11.50m, ImageUrl = "", CategoryId = mysteryId });
                    products.Add(new Product { Title = "The Girl with the Dragon Tattoo", Author = "Stieg Larsson", ISBN = "978-0307949486", Description = "Murder mystery, family saga, love story, and financial intrigue combined.", ListPrice = 17.00m, Price = 15.50m, Price50 = 14.00m, Price100 = 12.50m, ImageUrl = "", CategoryId = mysteryId });
                    products.Add(new Product { Title = "The Da Vinci Code", Author = "Dan Brown", ISBN = "978-0307474278", Description = "A gripping mix of history, art, code-breaking, and thriller.", ListPrice = 16.99m, Price = 15.00m, Price50 = 13.50m, Price100 = 12.00m, ImageUrl = "", CategoryId = mysteryId });
                    products.Add(new Product { Title = "And Then There Were None", Author = "Agatha Christie", ISBN = "978-0062073488", Description = "Ten strangers are invited to an isolated island, and they start dying one by one.", ListPrice = 14.99m, Price = 13.50m, Price50 = 12.00m, Price100 = 10.50m, ImageUrl = "", CategoryId = mysteryId });
                    products.Add(new Product { Title = "The Silence of the Lambs", Author = "Thomas Harris", ISBN = "978-0312924584", Description = "FBI trainee Clarice Starling seeks the help of Hannibal Lecter to catch a serial killer.", ListPrice = 15.99m, Price = 14.00m, Price50 = 12.50m, Price100 = 11.00m, ImageUrl = "", CategoryId = mysteryId });
                    products.Add(new Product { Title = "Big Little Lies", Author = "Liane Moriarty", ISBN = "978-0399167065", Description = "A brilliant take on ex-husbands and second wives, mothers and daughters, schoolyard scandal.", ListPrice = 16.99m, Price = 15.50m, Price50 = 14.00m, Price100 = 12.50m, ImageUrl = "", CategoryId = mysteryId });
                    products.Add(new Product { Title = "The Silent Patient", Author = "Alex Michaelides", ISBN = "978-1250301697", Description = "A shocking psychological thriller of a woman's act of violence against her husband.", ListPrice = 26.99m, Price = 24.50m, Price50 = 22.00m, Price100 = 19.50m, ImageUrl = "", CategoryId = mysteryId });
                    products.Add(new Product { Title = "Murder on the Orient Express", Author = "Agatha Christie", ISBN = "978-0062073501", Description = "Hercule Poirot investigates a murder on a luxurious train.", ListPrice = 14.99m, Price = 13.50m, Price50 = 12.00m, Price100 = 10.50m, ImageUrl = "", CategoryId = mysteryId });

                    // Business & Economics
                    int businessId = GetCatId("Business & Economics");
                    products.Add(new Product { Title = "Freakonomics", Author = "Steven D. Levitt & Stephen J. Dubner", ISBN = "978-0060731335", Description = "A rogue economist explores the hidden side of everything.", ListPrice = 16.99m, Price = 15.50m, Price50 = 14.00m, Price100 = 12.50m, ImageUrl = "", CategoryId = businessId });
                    products.Add(new Product { Title = "The Lean Startup", Author = "Eric Ries", ISBN = "978-0307887894", Description = "How today's entrepreneurs use continuous innovation to create radically successful businesses.", ListPrice = 28.00m, Price = 25.50m, Price50 = 23.00m, Price100 = 20.50m, ImageUrl = "", CategoryId = businessId });
                    products.Add(new Product { Title = "Zero to One", Author = "Peter Thiel", ISBN = "978-0804139298", Description = "Notes on startups, or how to build the future.", ListPrice = 27.00m, Price = 24.50m, Price50 = 22.00m, Price100 = 19.50m, ImageUrl = "", CategoryId = businessId });
                    products.Add(new Product { Title = "Thinking, Fast and Slow (Business Edition)", Author = "Daniel Kahneman", ISBN = "978-0374533557", Description = "The groundbreaking tour of the mind and explains the two systems that drive the way we think.", ListPrice = 20.00m, Price = 18.00m, Price50 = 16.50m, Price100 = 15.00m, ImageUrl = "", CategoryId = businessId });
                    products.Add(new Product { Title = "Good to Great", Author = "Jim Collins", ISBN = "978-0066620992", Description = "Why some companies make the leap and others don't.", ListPrice = 29.99m, Price = 27.00m, Price50 = 24.50m, Price100 = 22.00m, ImageUrl = "", CategoryId = businessId });
                    products.Add(new Product { Title = "The Intelligent Investor", Author = "Benjamin Graham", ISBN = "978-0060555665", Description = "The definitive book on value investing.", ListPrice = 24.99m, Price = 22.50m, Price50 = 20.00m, Price100 = 18.00m, ImageUrl = "", CategoryId = businessId });
                    products.Add(new Product { Title = "Rich Dad Poor Dad", Author = "Robert T. Kiyosaki", ISBN = "978-1612680194", Description = "What the rich teach their kids about money that the poor and middle class do not!", ListPrice = 18.99m, Price = 17.00m, Price50 = 15.50m, Price100 = 14.00m, ImageUrl = "", CategoryId = businessId });
                    products.Add(new Product { Title = "Start with Why", Author = "Simon Sinek", ISBN = "978-1591846444", Description = "How great leaders inspire everyone to take action.", ListPrice = 16.00m, Price = 14.50m, Price50 = 13.00m, Price100 = 11.50m, ImageUrl = "", CategoryId = businessId });

                    // Cooking & Food
                    int cookingId = GetCatId("Cooking & Food");
                    products.Add(new Product { Title = "Salt, Fat, Acid, Heat", Author = "Samin Nosrat", ISBN = "978-1476753836", Description = "Mastering the elements of good cooking.", ListPrice = 37.50m, Price = 34.00m, Price50 = 31.00m, Price100 = 28.00m, ImageUrl = "", CategoryId = cookingId });
                    products.Add(new Product { Title = "The Joy of Cooking", Author = "Irma S. Rombauer", ISBN = "978-1501169717", Description = "The most beloved and indispensable cookbook.", ListPrice = 40.00m, Price = 36.00m, Price50 = 33.00m, Price100 = 30.00m, ImageUrl = "", CategoryId = cookingId });
                    products.Add(new Product { Title = "Kitchen Confidential", Author = "Anthony Bourdain", ISBN = "978-0060899226", Description = "Adventures in the culinary underbelly.", ListPrice = 16.99m, Price = 15.50m, Price50 = 14.00m, Price100 = 12.50m, ImageUrl = "", CategoryId = cookingId });
                    products.Add(new Product { Title = "Mastering the Art of French Cooking", Author = "Julia Child", ISBN = "978-0375413407", Description = "The definitive guide to French cooking for American readers.", ListPrice = 40.00m, Price = 36.00m, Price50 = 33.00m, Price100 = 30.00m, ImageUrl = "", CategoryId = cookingId });
                    products.Add(new Product { Title = "The Food Lab", Author = "J. Kenji López-Alt", ISBN = "978-0393081084", Description = "Better home cooking through science.", ListPrice = 49.95m, Price = 45.00m, Price50 = 41.00m, Price100 = 37.00m, ImageUrl = "", CategoryId = cookingId });
                    products.Add(new Product { Title = "Plenty", Author = "Yotam Ottolenghi", ISBN = "978-1452101248", Description = "Vibrant vegetable recipes from London's Ottolenghi.", ListPrice = 35.00m, Price = 32.00m, Price50 = 29.00m, Price100 = 26.00m, ImageUrl = "", CategoryId = cookingId });
                    products.Add(new Product { Title = "Cravings", Author = "Chrissy Teigen", ISBN = "978-1101903919", Description = "Recipes for all the food you want to eat.", ListPrice = 29.99m, Price = 27.00m, Price50 = 24.50m, Price100 = 22.00m, ImageUrl = "", CategoryId = cookingId });
                    products.Add(new Product { Title = "On Food and Cooking", Author = "Harold McGee", ISBN = "978-0684800011", Description = "The science and lore of the kitchen.", ListPrice = 40.00m, Price = 36.00m, Price50 = 33.00m, Price100 = 30.00m, ImageUrl = "", CategoryId = cookingId });

                    if (products.Any())
                    {
                        _dbContext.Products.AddRange(products);
                        await _dbContext.SaveChangesAsync();
                    }
                }
            }
        }
    }
}
